### PR TITLE
Add an identity-based hash strategy

### PR DESCRIPTION
**Pull request by kashike**
This introduces a new `Hash.Strategy` that is identity based.

### CODE REVIEW

**Comment by vigna** [comment]
What are the advantages of an identity hash strategy over Reference containers? Just asking, the code is fine (and if you can email me your real name I'll add it to the CHANGES).

**Comment by kashike** [comment]
A wrapper (I assume this is what you mean by "reference container") could be used, but that is more "boilerplate" and you need to implement `equals`/`hashCode` yourself again.

`equals` and `hashCode` implementations can, at times, be (very) slow when they're using some sort of "builder" to check equality/generate a hash.

**Comment by liach** [comment]
i believe this strategy addition is better than extra wrapper objects memory-wise when the number of elements is large.

**Comment by kashike** [comment]
@vigna Any update to this?

**Comment by vigna** [comment]
No,  by "reference container" I mean something like "Reference2LongOpenHashMap", which use an identity-based hash strategy by default.

**Pull request closed without merging**
