### PR TITLE
Add a fast toArray to ArraySet.

### PR DESCRIPTION
**Pull request by techsy730**
Add a fast `toArray` to `ArraySet`

Also slightly expand the unit tests for object based `toArray`s

### CODE REVIEW

**Comment by vigna** [comment]
Hey, toArray() with a primitive-type array argument is deprecated upstream. I really think you have warnings disabled for deprecated methods, or you should see this. My suggestion is that of not implementing it at all (the docs say it will be removed in a future release).

**Comment by techsy730** [comment]
Oops, I thought I overrode the right primitive toArray. I guess not.

And yep, "Signal overriding or implementing deprecated method" was unchecked for me. Oops

**Comment by vigna** [comment]
Yeah, probably we will get rid of it in 9.0.0. One day.

**Comment by techsy730** [comment]
Actually, it is methods like `toIntArray(int[])` that are deprecated. It says `toArray(int[])` is the preferred one.

> ```java
	/** Returns a primitive type array containing the items of this collection.
	 *
	 * <p>Note that, contrarily to {@link Collection#toArray(Object[])}, this
	 * methods just writes all elements of this collection: no special
	 * value will be added after the last one.
	 *
	 * @param a if this array is big enough, it will be used to store this collection.
	 * @return a primitive type array containing the items of this collection.
	 * @see Collection#toArray(Object[])
	 * @deprecated Please use {@code toArray()} instead&mdash;this method is redundant and will be removed in the future.
	 */
	@Deprecated
	default KEY_TYPE[] TO_KEY_ARRAY(KEY_TYPE a[]) {
		return toArray(a);
	}

	/** Returns an array containing all of the elements in this collection; the runtime type of the returned array is that of the specified array.
	 *
	 * <p>Note that, contrarily to {@link Collection#toArray(Object[])}, this
	 * methods just writes all elements of this collection: no special
	 * value will be added after the last one.
	 *
	 * @param a if this array is big enough, it will be used to store this collection.
	 * @return a primitive type array containing the items of this collection.
	 * @see Collection#toArray(Object[])
	 */
	KEY_TYPE[] toArray(KEY_TYPE a[]);
```

**Comment by vigna** [comment]
Oops, I remembered incorrectly. Well, at least now you have the warning on :).

**Pull request merged**
