### PR TITLE
Add 'Automatic-Module-Name' entry to manifest

### PR DESCRIPTION
**Pull request by kashike**
adds #89

I've left out change to `CHANGES` as you haven't bumped the version from `8.1.1` and I'm not sure what your versioning plan is.

### CODE REVIEW

**Comment by kashike** [comment]
@vigna any chance this could be looked at soon?

**Comment by vigna** [comment]
OK, I merged, but I don't understand your comment above about leaving out `CHANGES`.

**Comment by vigna** [comment]
BTW, if you wanna be thanked you have to send me your real name ;).

**Comment by kashike** [comment]
Thanks for merging this, @vigna!

My comment about `CHANGES` was that I didn't make any changes to the [CHANGES](https://github.com/vigna/fastutil/blob/master/CHANGES) file as I didn't know how you handle that file.

My real name is `Joshua Popoff`.

**Comment by vigna** [comment]
Unfortunately you added the module to the standard build, but not to the OSGi build that is used when uploading to Maven Central. Could you have a look?

**Comment by kashike** [comment]
Sorry - I assumed entries from the manifest would have propagated. No experience with OSGi.

**Pull request merged**
