### PR TITLE
Cache class field ref into local

### PR DESCRIPTION
**Pull request by mouse0w0**

### CODE REVIEW

**Comment by vigna** [comment]
Er... why did you close it?

**Comment by mouse0w0** [comment]
Cache class field to local is completed. I will reopen it.

**Comment by mouse0w0** [comment]
After some fixes, the pull request can now be successfully built and has passed all unit tests. Looking forward to your guidance.

**Comment by vigna** [comment]
If you send me your name, I'll add a thank note to CHANGES.

**Comment by mouse0w0** [comment]
You can refer to me by my GitHub username, mouse0w0, due to privacy concerns.

**Pull request merged**
