### PR TITLE
Fix bug in ImmutableSubList iterator

### PR DESCRIPTION
**Pull request by goldfeder**
listIterator() on a sublist needs to correct its index to add "from" to it.

### CODE REVIEW

**Comment by vigna** [comment]
Ouch, that must have been there for a long time. Could you add a unit test for that in IntImmutableListTest? Thanks!

**Comment by goldfeder** [comment]
Done!

**Comment by vigna** [comment]
Thanks! If you want to be thanked in the CHANGES file let me know your real name.

**Comment by goldfeder** [comment]
Sure, why not. I'm Chanoch Goldfeder. Thanks!

**Comment by goldfeder** [comment]
Ugh I just realized I fixed this wrong. It fixes the iteration but breaks
other stuff. Correct fix coming in a few.

**Pull request merged**
