### PR TITLE
Make BooleanPredicate extend BooleanUnaryOperator

### PR DESCRIPTION
**Pull request by techsy730**
Make `BooleanPredicate` extend `BooleanUnaryOperator`, as it is a unary operation.

Also add a `identity` to `UnaryOperator`s (and a `negation` for `BooleanUnaryOperator`).

### CODE REVIEW

**Comment by techsy730** [comment]
Ignore the commits involving DirectBooleanSet; this is just a side effect of the merge from another branch. They are deleted in 
f4a48f5

**Comment by techsy730** [comment]
Ignore the commits involving DirectBooleanSet; this is just a side effect of the merge from another branch. They are deleted in
812c48.

**Comment by techsy730** [comment]
Actually, I can do this cleaner

**Comment by vigna** [comment]
Ok. We totally need a protocol. I just finished writing a UnaryOperator.drv to avoid ambiguity in List.replaceAll(). 🤷🏻‍♂️

**Comment by techsy730** [comment]
Yes, and I am using that UnaryOperator in a later commit

**Comment by vigna** [comment]
LOL ok sorry I thought we stepped onto each other's toes. 😅

**Comment by techsy730** [comment]
See https://github.com/vigna/fastutil/pull/210 for a cleaner PR

**Pull request closed without merging**
