### PR TITLE
List.sort methods as well as methods that dynamically choose a sorting algorithm

### PR DESCRIPTION
**Pull request by techsy730**
Add List.sort and List.unstableSort, as well as methods that dynamically choose algorithm in Arrays

### CODE REVIEW

**Comment by vigna** [comment]
Hey, can you put your real name where I put an "X" in CHANGES? Then we're ready for merge.

**Comment by techsy730** [comment]
Yes, you may use my real name. "C. Sean Young" is how I would prefer it to be listed.

**Comment by techsy730** [comment]
Quick question. Did you want this to be version 8.2.4 or 8.3.0?

**Comment by vigna** [comment]
8.3.0. In theory I should have already pit that in...

On July 31, 2019 7:31:21 PM GMT+02:00, TechSY730 <notifications@github.com> wrote:
>Quick question. Did you want this to be version 8.2.4 or 8.3.0?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vigna/fastutil/pull/130#issuecomment-516945866

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by techsy730** [comment]
Ok, do you want me to update build.properties or you do it?

**Comment by vigna** [comment]
You can do it! 

On July 31, 2019 7:37:51 PM GMT+02:00, TechSY730 <notifications@github.com> wrote:
>Ok, do you want me to update build.properties or you do it?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vigna/fastutil/pull/130#issuecomment-516948241

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by techsy730** [comment]
Also, I finally did a bit of profiling and found out radix sort becomes faster a lot earlier then I originally guessed.

**Comment by vigna** [comment]
Of course at some point one might be willing to do all of this for parallel sorts. But that's material for the future...

**Pull request merged**
